{
 "title": "CAST AI cluster metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Agent snapshost received total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(castai_autoscaler_agent_snapshots_received_total[$__interval])) by (castai_cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Agent snapshosts processed total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(castai_autoscaler_agent_snapshots_processed_total[$__interval])) by (castai_cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node spot interrupts total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(castai_spot_interrupts_total[$__interval])) by (castai_cluster)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Node placer unscheduled pods total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(castai_autoscaler_node_placer_unscheduled_pods_total[$__interval])) by (namespace,pod)",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Node add operations total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(castai_add_node_op_total[$__interval])) by (instance_type)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Node delete operations total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(castai_delete_node_op_total[$__interval])) by (instance_type)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Node add operations failures total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(castai_add_node_op_failures_total[$__interval])) by (instance_type)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Node delete operations failures total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(castai_delete_node_op_failures_total[$__interval])",
     "legendFormat": "{{instance_type}}"
    }
   ]
  }
 ]
}