apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-a
  labels:
    app: webserver-a
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver-a
  template:
    metadata:
      labels:
        app: webserver-a
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '150m'
              memory: '128Mi'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-b
  labels:
    app: webserver-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-b
  template:
    metadata:
      labels:
        app: webserver-b
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-c
  labels:
    app: webserver-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver-c
  template:
    metadata:
      labels:
        app: webserver-c
    spec:
      tolerations:
        - key: scheduling.cast.ai/spot
          operator: Exists
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: webserver-c
              weight: 100
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '100m'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-scoped
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-scoped
  template:
    metadata:
      labels:
        app: nginx-scoped
    node-selector:
    spec:
      topologySpreadConstraints:
        - maxSkew: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nginx-scoped
      tolerations:
        - key: scheduling.cast.ai/spot
          operator: Exists
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
            memory: 500Mi

