apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-spot
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-scoped
  template:
    metadata:
      labels:
        app: nginx-scoped
    node-selector:
    spec:
      nodeSelector:
        scheduling.cast.ai/spot: "true"
      tolerations:
      - key: "scheduling.cast.ai/spot"
        operator: Exists      
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 2
